### ISSUE TITLE
Websocket transport not available when using eventlet with the gunicorn web server

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/Flask-SocketIO#153]
An exception is thrown during the upgrade mechanism:

    12e130f2f9e3430da0b461d634f40649: Received request to upgrade to websocket
    [2015-10-13 23:28:00 +0000] [5684] [ERROR] Error handling request
    Traceback (most recent call last):
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
        self.handle_request(listener_name, req, client, addr)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/gunicorn/workers/async.py", line 105, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/engineio/middleware.py", line 32, in __call__
        return self.engineio_app.handle_request(environ, start_response)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/socketio/server.py", line 301, in handle_request
        return self.eio.handle_request(environ, start_response)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/engineio/server.py", line 224, in handle_request
        environ, start_response)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/engineio/socket.py", line 75, in handle_get_request
        start_response)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/engineio/socket.py", line 110, in _upgrade_websocket
        return ws(environ, start_response)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/eventlet-0.17.4-py2.7.egg/eventlet/websocket.py", line 113, in __call__
        ws = self._handle_hybi_request(environ)
      File "/home/miguel/Documents/dev/flask/flask-socketio/venv27/lib/python2.7/site-packages/eventlet-0.17.4-py2.7.egg/eventlet/websocket.py", line 195, in _handle_hybi_request
        sock = environ['eventlet.input'].get_socket()
    KeyError: 'eventlet.input'

**Comment by miguelgrinberg** [comment]
Fixed in python-engineio.

**Comment by nicksnell** [comment]
I'm still getting this issue with gunicorn and the flask dev server. Is there any change in setup thats needed to resolve this?

Using latest versions of Flask-SocketIO, python-engineio & python-socketio on Python 3.4.2 .

```
Traceback (most recent call last):
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/flask_socketio/__init__.py", line 24, in __call__
    start_response)
  File "/Users/ns/.venvs/policy/lib/python3.4/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/socketio/server.py", line 301, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/engineio/server.py", line 226, in handle_request
    environ, start_response)
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/engineio/socket.py", line 75, in handle_get_request
    start_response)
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/engineio/socket.py", line 110, in _upgrade_websocket
    return ws(environ, start_response)
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/eventlet/websocket.py", line 113, in __call__
    ws = self._handle_hybi_request(environ)
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/eventlet/websocket.py", line 195, in _handle_hybi_request
    sock = environ['eventlet.input'].get_socket()
KeyError: 'eventlet.input'
```

**Comment by nicksnell** [comment]
Example of my setup:

```python
socketio = SocketIO()

def create_app(package_name):
	app = Flask(package_name)

	socketio.init_app(app, engineio_logger=True, async_mode='eventlet')

	return app

app = create_app(__name__)
app.run()
```

If I change the server run to:

```
socketio.run(app)
```

I get a different error, but the websocket does connect (initial server error causes an error on client side too):

```
Traceback (most recent call last):
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/eventlet/wsgi.py", line 498, in handle_one_response
    write(b'')
  File "/Users/ns/.venvs/p/lib/python3.4/site-packages/eventlet/wsgi.py", line 391, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()
```

**Comment by miguelgrinberg** [comment]
What's the output of `pip freeze` in your virtualenv?

**Comment by incognick** [comment]
I think I'm getting the same error.  I'm trying the example on the docs page.  I'm using Python 2.7 and I'm grafting the Flask app on the cherrypy tree. Should this work through WSGI?  

```python
from flask import Flask, render_template
from flask_socketio import SocketIO, send, emit

app = Flask(__name__)
app.logger_name = 'api'
app.config['SECRET_KEY'] = 'secret!'

socketio = SocketIO(app)

import logging
log = logging.getLogger('api')

#import conf.config as config

@app.route('/')
def index():
    return render_template('index.html')


@socketio.on('my event')
def handl_event(data):
    log.info('Recieved data: %s'%(data))
    emit('my response', data)

# More complicated than this but placed here for example
cherrypy.tree.graft(app, '/')
```

Output

```
2015-11-23 15:28:39.167  INFO engineio CP Server Thread-5: send::socket.py:63  fe4511bf6ac140619a1f792f8c2b68de: Sending packet OPEN with {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': 'fe4511bf6ac140619a1f792f8c2b68de'}
2015-11-23 15:28:39.168  INFO engineio CP Server Thread-5: send::socket.py:63  fe4511bf6ac140619a1f792f8c2b68de: Sending packet MESSAGE with 0
2015-11-23 15:28:39.364  INFO engineio CP Server Thread-5: receive::socket.py:40  fe4511bf6ac140619a1f792f8c2b68de: Received packet MESSAGE with 2["my event",{"data":"I'm connected!"}]
2015-11-23 15:28:39.365  INFO socketio CP Server Thread-5: _handle_event::server.py:357  received event "my event" from fe4511bf6ac140619a1f792f8c2b68de [/]
2015-11-23 15:28:39.365  INFO api CP Server Thread-5: handl_event::application.py:22  Recieved data: {u'data': u"I'm connected!"}
2015-11-23 15:28:39.365  INFO socketio CP Server Thread-5: emit::server.py:177  emitting event "my response" to fe4511bf6ac140619a1f792f8c2b68de [/]
2015-11-23 15:28:39.366  INFO engineio CP Server Thread-5: send::socket.py:63  fe4511bf6ac140619a1f792f8c2b68de: Sending packet MESSAGE with 2["my response",{"data":"I'm connected!"}]
2015-11-23 15:28:40.387  INFO engineio CP Server Thread-4: handle_get_request::socket.py:73  fe4511bf6ac140619a1f792f8c2b68de: Received request to upgrade to websocket
2015-11-23 15:28:40.390  ERROR cherrypy.error CP Server Thread-4: error::_cplogging.py:216  [23/Nov/2015:15:28:40] ENGINE KeyError('eventlet.input',)
Traceback (most recent call last):
  File "XXX/install/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1353, in communicate
    req.respond()
  File "XXX/install/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 868, in respond
    self.server.gateway(self).respond()
  File "XXX/install/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2267, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "XXX/install/lib/python2.7/site-packages/cherrypy/_cptree.py", line 299, in __call__
    return app(environ, start_response)
  File "XXX/install/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "XXX/install/lib/python2.7/site-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "XXX/install/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "XXX/install/lib/python2.7/site-packages/socketio/server.py", line 300, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "XXX/install/lib/python2.7/site-packages/engineio/server.py", line 226, in handle_request
    environ, start_response)
  File "XXX/install/lib/python2.7/site-packages/engineio/socket.py", line 75, in handle_get_request
    start_response)
  File "XXX/install/lib/python2.7/site-packages/engineio/socket.py", line 110, in _upgrade_websocket
    return ws(environ, start_response)
  File "XXX/install/lib/python2.7/site-packages/eventlet/websocket.py", line 113, in __call__
    ws = self._handle_hybi_request(environ)
  File "XXX/install/lib/python2.7/site-packages/eventlet/websocket.py", line 195, in _handle_hybi_request
    sock = environ['eventlet.input'].get_socket()
KeyError: 'eventlet.input'
```

```
./pip freeze
CherryPy==3.8.0
eventlet==0.17.4
Flask==0.10.1
Flask-HTTPAuth==2.5.0
Flask-SocketIO==1.1
greenlet==0.4.9
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
python-engineio==0.8.0
python-socketio==0.7.0
pyzmq==14.7.0
six==1.10.0
storm==0.19.0.99
Werkzeug==0.11.2
wheel==0.24.0
```

**Comment by miguelgrinberg** [comment]
I'm not familiar with the cherrypy web server. Is it compatible with eventlet? I bet it isn't, the error indicates that this special addition to the WSGI protocol that eventlet adds to implement websocket isn't present in the requests. Use eventlet's own web server and you should be fine, or if you prefer to use cherrypy and are okay not using WebSocket, make sure it is configured to handle requests in multithreaded fashion and disable WebSocket in the SocketIO constructor.

**Comment by incognick** [comment]
Thanks Miguel. It doesn't look like what I want to do is easily supported
using CherryPy. I will switch to gevent for this project to take advantage
of SocketIO.

**Comment by miguelgrinberg** [comment]
@incognick Note that you have installed eventlet in your virtualenv. Eventlet and gevent are different and incompatible. Flask-SocketIO gives you the option to use either one. If you want to use gevent, then uninstall eventlet from your virtualenv, and then install gevent and gevent-websocket.

As a side note, if you consider ever porting your app to Python 3, then eventlet is much more stable on that version than gevent, which only recently was ported.

**Comment by NeilHanlon** [comment]
@miguelgrinberg Hey! I'm having a similar issue with my app.. just running pure flask-socketio...

    127.0.0.1 - - [08/Dec/2015 23:49:44] "GET / HTTP/1.1" 200 -
    127.0.0.1 - - [08/Dec/2015 23:49:44] "GET /socket.io/?EIO=3&transport=polling&t=1449636584971-0 HTTP/1.1" 200 -
    127.0.0.1 - - [08/Dec/2015 23:49:45] "GET /socket.io/?EIO=3&transport=websocket&sid=2ea9be15f43e448b9267689f41e5c2fb HTTP/1.1" 500 -
    Traceback (most recent call last):
      File "C:\Users\..\.venv\lib\site-packages\flask\app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "C:\Users\..\.venv\lib\site-packages\flask_socketio\__init__.py", line 37, in __call__
        start_response)
      File "C:\Users\..\.venv\lib\site-packages\engineio\middleware.py", line 47, in __call__
        return self.engineio_app.handle_request(environ, start_response)
      File "C:\Users\..\.venv\lib\site-packages\socketio\server.py", line 300, in handle_request
        return self.eio.handle_request(environ, start_response)
      File "C:\Users\..\.venv\lib\site-packages\engineio\server.py", line 226, in handle_request
        environ, start_response)
      File "C:\Users\..\.venv\lib\site-packages\engineio\socket.py", line 75, in handle_get_request
        start_response)
      File "C:\Users\..\.venv\lib\site-packages\engineio\socket.py", line 110, in _upgrade_websocket
        return ws(environ, start_response)
      File "C:\Users\..\.venv\lib\site-packages\eventlet\websocket.py", line 113, in __call__
        ws = self._handle_hybi_request(environ)
      File "C:\Users\..\.venv\lib\site-packages\eventlet\websocket.py", line 195, in _handle_hybi_request
        sock = environ['eventlet.input'].get_socket()
    KeyError: 'eventlet.input'


Any thoughts?

**Comment by miguelgrinberg** [comment]
@NeilHanlon My guess is that you are setting the async_mode to eventlet, but don't have eventlet installed.

**Comment by NeilHanlon** [comment]
@miguelgrinberg I'm setting the async_mode, yes--but eventlet is installed in the virtualenv.

**Comment by miguelgrinberg** [comment]
Are you running gunicorn? If yes, you have to use the event let worker, see
the docs for the command.

**Comment by NeilHanlon** [comment]
Nope—just straight up flask.

**Comment by miguelgrinberg** [comment]
There's something I must be missing then. If you are running `socketio.run(app)`, and you have eventlet installed, then there is no reason for the `eventlet.input` key to be missing in the WSGI environment.

**Comment by NeilHanlon** [comment]
I'm more or less following the model you use in your Flask-SocketIO-Chat repo, where the handlers are defined as a blueprint.. for example:

**.\\server.py:**

    from websocket_server import create_server, socketio

    if __name__ == '__main__':

        server = create_server()

        server.run(debug=True, host="0.0.0.0", port=6001)

**websocket_server\\\__init__.py:**

    from flask_socketio import SocketIO
    from flask import Flask, request, session, render_template
    import eventlet

    socketio = SocketIO()

    def create_server():
        server = Flask(__name__)

        from .main import main as main_blueprint
        server.register_blueprint(main_blueprint)

        server.config["SECRET_KEY"] = "ajglkj120398j9fa8sjd123!~!#"

        @server.route('/')
        def index():
            return render_template("websockets.html")

        socketio.init_app(server)

        return server

**websocket_server\\main\\\__init__.py:**

    from flask import Blueprint

    main = Blueprint('main', __name__)

    import events

**websocket_server\\main\\events.py:**

    from flask import session, request
    from flask_socketio import emit, join_room, leave_room, \
        close_room, rooms, disconnect
    from .. import socketio

    @socketio.on('my event', namespace='/test')
    def test_message(message):
        session['receive_count'] = session.get('receive_count', 0) + 1
        emit('my response',
             {'data': message['data'], 'count': session['receive_count']})

    [snipped]

I run server.py to run the socketio/flask server.

This is a dump of the environ variable that eventlet\\websocket.py is looking in:

    {
        'CONTENT_LENGTH': '',
        'CONTENT_TYPE': '',
        'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
        'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
        'HTTP_CACHE_CONTROL': 'no-cache',
        'HTTP_CONNECTION': 'Upgrade',
        'HTTP_COOKIE': 'io=7360a2b637eb41258134b04c6c6094d2',
        'HTTP_HOST': 'localhost:6001',
        'HTTP_ORIGIN': 'http://localhost:6001',
        'HTTP_PRAGMA': 'no-cache',
        'HTTP_SEC_WEBSOCKET_EXTENSIONS': 'permessage-deflate; client_max_window_bits',
        'HTTP_SEC_WEBSOCKET_KEY': 'BYdTQzncFdMWt6DMyCPpbw==',
        'HTTP_SEC_WEBSOCKET_VERSION': '13',
        'HTTP_UPGRADE': 'websocket',
        'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 YaBrowser/15.10.2454.3865 Safari/537.36',
        'PATH_INFO': '/socket.io/',
        'QUERY_STRING': 'EIO=3&transport=websocket&sid=7360a2b637eb41258134b04c6c6094d2',
        'REMOTE_ADDR': '127.0.0.1',
        'REMOTE_PORT': 61589,
        'REQUEST_METHOD': 'GET',
        'SCRIPT_NAME': '',
        'SERVER_NAME': '0.0.0.0',
        'SERVER_PORT': '6001',
        'SERVER_PROTOCOL': 'HTTP/1.1',
        'SERVER_SOFTWARE': 'Werkzeug/0.10.4',
        'flask.app': <Flask 'websocket_server'>,
        'werkzeug.request': <BaseRequest 'http://localhost:6001/socket.io/?EIO=3&transport=websocket&sid=7360a2b637eb41258134b04c6c6094d2' [GET]>,
        'werkzeug.server.shutdown': <function shutdown_server at 0x02A7F8F0>,
        'wsgi.errors': <open file '<stderr>', mode 'w' at 0x024BD0D0>,
        'wsgi.input': <socket._fileobject object at 0x02A7F8B0>,
        'wsgi.multiprocess': False,
        'wsgi.multithread': False,
        'wsgi.run_once': False,
        'wsgi.url_scheme': 'http',
        'wsgi.version': (1, 0)
    }

**Comment by miguelgrinberg** [comment]
Use `socketio.run(app)` to start the server, not `server.run()`. A standard WSGI server like the Werkzeug one cannot support WebSocket. When you run the server through `socketio.run` things are hooked up so that eventlet's server is used.

**Comment by NeilHanlon** [comment]
Whoops. I feel dumb.

Nice catch.

Thanks!

**Comment by anestin-femi** [comment]
i am having the same problem. the socket io work well on my test machine , but my production server does not get to see socket.
